### ISSUE TITLE
The scan results doesn't return `fixPath`

### ISSUE THREAD

**Issue by Ciggzy1312** [kubescape/node-kubescape#1]
The `cmd` which scans the YAML files is not returning `fixPath` when used with the relative path of kubescape which for example is `"/home/deepayan/Desktop/OSS/Kubescape/vscode-kubescape/install/kubescape"`. But when used with the absolute path that is only `kubescape` the scanned results do have `fixPath` in them

This might be happening because both of them are not pointing to the same version of kubescape.

**Comment by amirmalka** [comment]
@Ciggzy1312 we have release a new version of the `@kubescape/install` package which works with the latest Kubescape version. Please let me know if this issue can be closed.

**Comment by amirmalka** [comment]
@Ciggzy1312 can this issue be close?
